### PR TITLE
Update to 5.11.1

### PR DESCRIPTION
**Pull request by tobyink**
Updates taken from https://github.com/geoclaps/advanced-custom-fields-pro

### CODE REVIEW

**Comment by tobyink** [comment]
5.9.4 from https://github.com/hristov296/advanced_custom_fields_pro

**Comment by dieppon** [comment]
Can the last commit be tagged as a release?

**Comment by tobyink** [comment]
5.9.9 from https://github.com/aminesayagh/advanced-custom-fields-pro

**Comment by tobyink** [comment]
5.10.2 from https://github.com/wordpress-premium/advanced-custom-fields-pro/

**Comment by tobyink** [comment]
5.11.1 from https://github.com/wordpress-premium/advanced-custom-fields-pro/

**Comment by tobyink** [comment]
5.11.4 from https://github.com/wordpress-premium/advanced-custom-fields-pro/

**Pull request closed without merging**
